import os
import logging

logger = logging.getLogger("karaoke")

def format_time(seconds: float) -> str:
    """Converte segundos para o formato de tempo do ASS: H:MM:SS.CS (Centisegundos)."""
    h = int(seconds // 3600)
    m = int((seconds % 3600) // 60)
    s = int(seconds % 60)
    cs = int(round((seconds - int(seconds)) * 100))
    
    # Tratar overflow de arredondamento
    if cs == 100:
        s += 1
        cs = 0
    if s == 60:
        m += 1
        s = 0
    if m == 60:
        h += 1
        m = 0
        
    return f"{h}:{m:02d}:{s:02d}.{cs:02d}"

def html_color_to_ass(hex_color: str) -> str:
    """Converte cores hexadecimais HTML (#RRGGBB) para o formato ASS (&H00BBGGRR)."""
    hex_color = hex_color.lstrip('#')
    if len(hex_color) == 6:
        r, g, b = hex_color[0:2], hex_color[2:4], hex_color[4:6]
        # ASS usa formato Alpha-Blue-Green-Red (AABBGGRR)
        return f"&H00{b}{g}{r}"
    return "&H0000FFFF" # Amarelo padrão se falhar

def generate_ass_karaoke(
    segments: list[dict], 
    output_ass_path: str,
    font_size: int = 32,
    text_color_hex: str = "#00FFFF",
    text_position: str = "bottom"
):
    """
    Gera um arquivo de legenda ASS customizado.
    Mapeia tamanho, cor de destaque e alinhamento do texto.
    """
    logger.info(f"Gerando legenda ASS customizada: fonte={font_size}, cor={text_color_hex}, pos={text_position}")
    
    # 1. Determinar o alinhamento ASS (2 = base centro, 5 = meio centro, 8 = topo centro)
    alignment = 2
    if text_position == "middle":
        alignment = 5
    elif text_position == "top":
        alignment = 8

    # 2. Converter a cor RGB do HTML para o formato BGR do ASS
    ass_highlight_color = html_color_to_ass(text_color_hex)
    
    # Cabeçalho padrão do ASS com estilos e configurações de tela ajustadas
    ass_header = f"""[Script Info]
; Script generated by Sal0 karaoke
Title: Sal0 Karaoke Legenda
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes
PlayResX: 1280
PlayResY: 720

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Arial,{font_size},&H00FFFFFF,{ass_highlight_color},&H00000000,&H00000000,1,0,0,0,100,100,0,0,1,3,1,{alignment},20,20,50,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
"""

    lines = [ass_header]
    
    for seg in segments:
        start_time_str = format_time(seg["start"])
        end_time_str = format_time(seg["end"])
        
        # Construir o texto da legenda formatado para karaoke
        karaoke_text = ""
        current_ref = seg["start"]
        
        for word_info in seg["words"]:
            word_text = word_info["word"]
            w_start = word_info["start"]
            w_end = word_info["end"]
            
            # 1. Tratar silêncios intermediários/iniciais (gaps)
            if w_start > current_ref:
                gap_dur = w_start - current_ref
                gap_cs = int(round(gap_dur * 100))
                if gap_cs > 0:
                    karaoke_text += f"{{\\kf{gap_cs}}}"
                current_ref = w_start
                
            # 2. Calcular a duração da palavra (mínimo de 5 centisegundos para segurança)
            word_dur = w_end - w_start
            if word_dur <= 0:
                word_dur = 0.05
            word_cs = int(round(word_dur * 100))
            
            # 3. Separar espaços laterais para que a tag de transição de cor (\kf)
            # pinte somente as letras em si, evitando comportamento visual indesejado.
            leading_spaces = len(word_text) - len(word_text.lstrip(' '))
            trailing_spaces = len(word_text.lstrip(' ')) - len(word_text.strip(' '))
            clean_text = word_text.strip(' ')
            
            if clean_text:
                spaces_before = " " * leading_spaces
                spaces_after = " " * trailing_spaces
                karaoke_text += f"{spaces_before}{{\\kf{word_cs}}}{clean_text}{spaces_after}"
            else:
                # Se for apenas espaço
                karaoke_text += f"{{\\kf{word_cs}}}{word_text}"
                
            current_ref = w_end
            
        # 4. Tratar silêncio final (caso o segmento termine após a última palavra)
        if seg["end"] > current_ref:
            trail_dur = seg["end"] - current_ref
            trail_cs = int(round(trail_dur * 100))
            if trail_cs > 0:
                karaoke_text += f"{{\\kf{trail_cs}}}"
                
        # Adicionar a linha de diálogo formatada no padrão ASS
        # Dialogue: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
        line = f"Dialogue: 0,{start_time_str},{end_time_str},Default,,0,0,0,,{karaoke_text}\n"
        lines.append(line)
        
    # Escrever no arquivo final
    with open(output_ass_path, "w", encoding="utf-8") as f:
        f.writelines(lines)
        
    logger.info("Legenda ASS gerada com sucesso.")
